version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -ifNotExists"
